version: "3.7"

services:
  app:
    image: embarkstudios/wireguard-ui:userspace
    entrypoint: "/wireguard-ui"
    privileged: true
    network_mode: "host"
    volumes:
      - /opt/wireguard-ui:/data
    environment:
      - WIREGUARD_UI_LOG_LEVEL=debug
      - WIREGUARD_UI_DATA_DIR=/data
      - WIREGUARD_UI_LISTEN_ADDRESS=:8080
      - WIREGUARD_UI_NAT=true
      - WIREGUARD_UI_NET_DEVICE=eth0
      - WIREGUARD_UI_CLIENT_IP_RANGE="172.31.255.0/24"
      #- WIREGUARD_UI_AUTH_USER_HEADER=X-Forwarded-User
      #- WIREGUARD_UI_MAX_NUMBER_CLIENT_CONFIG=0

      - WIREGUARD_UI_WG_DEVICE_NAME=wg0
      - WIREGUARD_UI_WG_LISTEN_PORT=51820
      - WIREGUARD_UI_WG_ENDPOINT=your-andpoint-address:51820
      #- WIREGUARD_UI_WG_ALLOWED_IPS="0.0.0.0/0"
      #- WIREGUARD_UI_WG_DNS=192.168.10.0
      #- WIREGUARD_UI_WG_KEEPALIVE=20

      #- WIREGUARD_UI_DEV_UI_SERVER=dev-server-endpoint
    restart: always
